name: TeamWin [TWRP]

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'TWRP Manifest Branch'
        required: true
        default: 'twrp-12.1'
        type: choice
        options:
        - twrp-14.1
        - twrp-14
        - twrp-12.1
        - twrp-11
        - twrp-10.0-deprecated
        - twrp-9.0
        - twrp-8.1
        - twrp-8.1-macOS
        - twrp-7.1
        - twrp-6.0
        - twrp-5.1
        - twrp-4.4-deprecated
      DEVICE_TREE:
        description: 'Custom Recovery Tree'
        required: true
        default: 'https://github.com/username/repo'
      DEVICE_TREE_BRANCH:
        description: 'Custom Recovery Tree Branch'
        required: true
        default: 'main'
      DEVICE_PATH:
        description: 'DEVICE_PATH'
        required: true
        default: 'device/brand/codename'
      DEVICE_NAME:
        description: 'DEVICE_NAME (Codename)'
        required: true
        default: ''
      MAKEFILE_NAME:
        description: 'MAKEFILE_NAME (excluding .mk extension, Example: omni_codename)'
        required: true
        default: 'omni_'
      EXTRA_TREE:
        description: 'Extra Tree (e.g., common tree repo)'
        required: false
        default: ''
      
      EXTRA_TREE_BRANCH:
        description: 'Extra Tree Branch'
        required: false
        default: 'main'
      
      EXTRA_PATH:
        description: 'Path to clone extra tree (e.g., device/brand/common)'
        required: false
        default: ''
      BUILD_TARGET:
        description: 'Specify your Build Target'
        required: true
        default: 'recovery'
        type: choice
        options:
        - boot
        - recovery
        - vendorboot
      LDCHECK:
        description: 'Use LDCHECK'
        required: false
        default: 'false'
        type: boolean
      LDCHECKPATH:
        description: 'Path of blobs to check'
        required: true
        default: 'system/bin/qseecomd'

jobs:
  build:
    name: Build TWRP by ${{ github.actor }}
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - name: Check Out
      uses: actions/checkout@v4
      
    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main
      
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Check Manifest Branch
      run: |
        if [ "${{ inputs.MANIFEST_BRANCH }}" == "twrp-11" ] || [ "${{ inputs.MANIFEST_BRANCH }}" == "twrp-12.1" ] || [ "${{ inputs.MANIFEST_BRANCH }}" == "twrp-14" ]; then
            echo "MANIFEST=https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git" >> $GITHUB_ENV
            echo "CHECK_LEGACY_BRANCH=false" >> $GITHUB_ENV
        else
            echo "MANIFEST=https://github.com/mlm-games/platform_manifest_twrp_omni.git" >> $GITHUB_ENV
            echo "CHECK_LEGACY_BRANCH=true" >> $GITHUB_ENV
        fi

    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y upgrade
        sudo add-apt-repository universe
        sudo apt -y install python2
        sudo ln -sf /usr/bin/python2 /usr/bin/python
        sudo apt -y install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib \
        libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev \
        libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev \
        lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev \
        libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev \
        lzma ncftp qemu-user-static libstdc++-10-dev libtinfo5 libgflags-dev libncurses5
        
    - name: Install OpenJDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Install Git-Repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Initialize Repo
      run: |
        mkdir android-recovery
        cd android-recovery
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        repo init --depth=1 -u ${{ env.MANIFEST }} -b ${{ inputs.MANIFEST_BRANCH }}

    - name: Repo Sync
      run: |
        cd android-recovery
        repo sync -j$(nproc --all) --force-sync

    - name: Detect TWRP Version
      run: |
       cd android-recovery

       TWRP_VERSION=$(grep -oP 'TW_MAIN_VERSION_STR\s+"\K[^"]+' bootable/recovery/variables.h)

       if [ -z "$TWRP_VERSION" ]; then
         echo "Could not detect TWRP version"
         TWRP_VERSION="unknown"
       fi

       echo "Detected TWRP version: $TWRP_VERSION"
       echo "TWRP_VERSION=$TWRP_VERSION" >> $GITHUB_ENV
      
    - name: Clone Device Tree
      run: |
        cd android-recovery
        git clone ${{ inputs.DEVICE_TREE }} -b ${{ inputs.DEVICE_TREE_BRANCH }} ./${{ inputs.DEVICE_PATH }}
        cd ${{ inputs.DEVICE_PATH }}
        
        COMMIT_ID=$(git rev-parse HEAD)
        SHORT_COMMIT_ID=$(git rev-parse --short HEAD)
        COMMIT_TITLE=$(git log -1 --pretty=%s)
        
        echo "COMMIT_ID=$COMMIT_ID" >> $GITHUB_ENV
        echo "SHORT_COMMIT_ID=$SHORT_COMMIT_ID" >> $GITHUB_ENV
        echo "COMMIT_TITLE=$COMMIT_TITLE" >> $GITHUB_ENV
            
    - name: Set Build Date
      run: |
        echo "BUILD_DATE=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

    - name: Apply source patches
      run: |
        cd android-recovery/bootable/recovery

        PATCH_DIR="../../${{ inputs.DEVICE_PATH }}/patches"

        if [ -d "$PATCH_DIR" ]; then
          echo "Applying patches from $PATCH_DIR"

          for patch in $PATCH_DIR/*.patch; do
            [ -f "$patch" ] || continue
            echo "Applying $patch"

            git apply "$patch" || {
              echo "git apply failed, trying fallback..."
              git apply --reject --whitespace=fix "$patch" || exit 1
            }
          done
        else
          echo "No patches directory found"
        fi

    - name: Installing python2 for legacy builds
      if: env.CHECK_LEGACY_BRANCH == 'true'
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa -y
        sudo apt-get update
        sudo apt-get install python2.7 -y
        sudo ln -sf /usr/bin/python2.7 /usr/bin/python
        sudo ln -sf /usr/bin/python2.7 /usr/bin/python2
        python --version

    - name: Building Image 
      run: |
        cd android-recovery
        set +e
        source build/envsetup.sh
        set -e
        
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch ${{ inputs.MAKEFILE_NAME }}-eng || { echo "Lunch failed"; exit 1; }

        make clean

        STD_OUT_DIR="out/target/product/${{ inputs.DEVICE_NAME }}"
        ERR_OUT_DIR="out/target/product/${{ inputs.DEVICE_NAME }}/target/product/${{ inputs.DEVICE_NAME }}"
        DTB_SRC="${{ inputs.DEVICE_PATH }}/prebuilt/dtb.img"

        echo "Creating output directories..."
        mkdir -p "$STD_OUT_DIR"
        mkdir -p "$ERR_OUT_DIR"

        if [ -f "$DTB_SRC" ]; then
            echo "Injecting DTB into output locations..."
            cp "$DTB_SRC" "$STD_OUT_DIR/dtb.img"
            cp "$DTB_SRC" "$ERR_OUT_DIR/dtb.img"
            touch "$STD_OUT_DIR/dtb.img"
            touch "$ERR_OUT_DIR/dtb.img"
            echo "DTB Injection successful."
        else
            echo "::warning::dtb.img not found at $DTB_SRC"
        fi

        make ${{ inputs.BUILD_TARGET }}image -j$(nproc --all)
        echo "Done building your ${{ inputs.BUILD_TARGET }}.img"

    - name: Rename Build Output
      run: |
        cd android-recovery/out/target/product/${{ inputs.DEVICE_NAME }}

        VERSION="${{ env.TWRP_VERSION }}"
        CODENAME="${{ inputs.DEVICE_NAME }}"
        DATE="${{ env.BUILD_DATE }}"

        if [ -f "${{ inputs.BUILD_TARGET }}.img" ]; then
          mv ${{ inputs.BUILD_TARGET }}.img twrp-${VERSION}-${CODENAME}-${DATE}.img
        fi

    - name: Upload to Release
      if: success()
      uses: softprops/action-gh-release@v2
      with:
        files: |
          android-recovery/out/target/product/${{ inputs.DEVICE_NAME }}/twrp-*.img
          android-recovery/out/target/product/${{ inputs.DEVICE_NAME }}/*installer*zip
          android-recovery/out/target/product/${{ inputs.DEVICE_NAME }}/ramdisk-recovery.*
          android-recovery/out/target/product/${{ inputs.DEVICE_NAME }}/vbmeta.*
        name: Unofficial TWRP for ${{ inputs.DEVICE_NAME }} [${{ env.SHORT_COMMIT_ID }}] // ${{ env.BUILD_DATE }}
        tag_name: build-${{ env.BUILD_DATE }}
        body: |
          Build: ${{ inputs.MANIFEST_BRANCH }}
          Device: [Device Tree](${{ inputs.DEVICE_TREE }})
          Branch: ${{ inputs.DEVICE_TREE_BRANCH }}
          Commit: [${{ env.COMMIT_ID }}](${{ inputs.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }}) [${{ env.COMMIT_TITLE }}]
          Image Build Target: ${{ inputs.BUILD_TARGET }}
        prerelease: true

    - name: Run LDCheck
      if: inputs.LDCHECK == 'true'
      run: |
        cd tools
        mv -n libneeds ${GITHUB_WORKSPACE}/android-recovery/out/target/product/${{ inputs.DEVICE_NAME }}/recovery/root/ || true
        mv -n ldcheck ${GITHUB_WORKSPACE}/android-recovery/out/target/product/${{ inputs.DEVICE_NAME }}/recovery/root/ || true
        cd ../android-recovery/out/target/product/${{ inputs.DEVICE_NAME }}/recovery/root
        python3 ldcheck -p system/lib64:vendor/lib64:system/lib:vendor/lib -d ${{ inputs.LDCHECKPATH }}
      continue-on-error: true
